### PR TITLE
Speed up the fromJSON method of the camera module

### PR DESCRIPTION
**Pull request by graugans**
This will not create a separate edit session for each top level entry in the
JSON object. The idea is creating one session and keeping this session
open until all entries are operated.

Signed-off-by: Christian Ege <christian.ege@ifm.com>

### CODE REVIEW

**Comment by tpanzarella** [comment]
@graugans Merging this PR results in a consistent failing of the unit tests. For example:

```
[ RUN      ] CameraTest.ActiveApplication
/home/uspanzto/dev/ifm3d/modules/camera/test/ifm3d-camera-camera-tests.cpp:252: Failure
Expected: this->cam_->FromJSONStr(R"({"Apps":[{}]})") doesn't throw an exception.
  Actual: it throws.
/home/uspanzto/dev/ifm3d/modules/camera/test/ifm3d-camera-camera-tests.cpp:255: Failure
Value of: 2
Expected: app_list.size()
Which is: 1
/home/uspanzto/dev/ifm3d/modules/camera/test/ifm3d-camera-camera-tests.cpp:267: Failure
Value of: 2
Expected: idx
Which is: -1
/home/uspanzto/dev/ifm3d/modules/camera/test/ifm3d-camera-camera-tests.cpp:281: Failure
Value of: 2
Expected: idx
Which is: -1
/home/uspanzto/dev/ifm3d/modules/camera/test/ifm3d-camera-camera-tests.cpp:284: Failure
Expected: this->cam_->DeleteApplication(idx) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] CameraTest.ActiveApplication (9187 ms)
```

**Comment by graugans** [comment]
@tpanzarella is it possible to have the benchmark branch public? At the moment I do not see any benefit of the undocumented ``-s`` switch for ifm3d as long as we do not provide and embedded version of ifm3d.

**Comment by tpanzarella** [comment]
>  is it possible to have the benchmark branch public?

Done. `dev-0.10.0_bench` It is undocumented, if you follow along with what I have done in PDS you should be able to use this. Hit me up on Teams if you need further help there.

> At the moment I do not see any benefit of the undocumented -s switch for ifm3d as long as we do not provide and embedded version of ifm3d.

Undocumented? ... I think taking it out for desktop builds is fine too. Maybe we wrap it in a `CMAKE_CROSSCOMPILING` conditional so that we put it back for embedded builds.

**Comment by graugans** [comment]
Undocumented because I just overlooked it and was searching down the Internet why my debug symbols are erased. Which drove me almost crazy.

**Comment by graugans** [comment]
From my point of view the pull request is ready. I have tested on O3D3xx and O3X both with the latest FW.

**Pull request merged**
