### PR TITLE
Fix issues with invalid pixels during make check

### PR DESCRIPTION
**Pull request by graugans**
If there are invalid pixels in the current frame the calculation of XYZ from distance data and are different than the values provided by the camera. This fix uses the confidence matrix as a mask for not checking invalid pixels

### CODE REVIEW

**Comment by graugans** [comment]
I will not available until November 5th. From my experience NaN is sometimes a false friend, in the past a bunch of software have not handled it correct. From  [cppreference.com](https://en.cppreference.com/w/cpp/types/numeric_limits/quiet_NaN) ``std::numeric_limits<float>::quiet_NaN`` only makes sense when the platform defines ``std::numeric_limits<T>::has_quiet_NaN == true``. From my point of view this is the benefit of the user-defined image container the user has full control and decide on his own. For the image container and the OpenCV container we can use the same implementation like in libo3d3xx. With the risk the platform has ``std::numeric_limits<T>::has_quiet_NaN == false``.

**Comment by graugans** [comment]
@tpanzarella looks like you also had higher priority tasks. When do you think you'll have the cycles to discuss the options?

**Comment by tpanzarella** [comment]
@graugans We can discuss further tomorrow on our call.

**Comment by tpanzarella** [comment]
This has been implemented in 0.11.1 at the driver level. Can you validate that this alleviates the issue of "invalid pixels during make check" per the original title of this PR.

**Comment by inbangsa** [comment]
**For O3D301 With Firmware 1.23.1256** 

Test are still failing.   

```
make check 
[ 22%] Built target ifm3d_camera_shared
[ 37%] Built target ifm3d_framegrabber_shared
[ 44%] Built target ifm3d_image_shared
[ 51%] Built target gtest
[ 59%] Built target gtest_main
[ 70%] Built target ifm3d-image-tests
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from Image
[ RUN      ] Image.MoveCtor
[       OK ] Image.MoveCtor (143 ms)
[ RUN      ] Image.MoveAssignmentOperator
[       OK ] Image.MoveAssignmentOperator (199 ms)
[ RUN      ] Image.CopyCtor
[       OK ] Image.CopyCtor (202 ms)
[ RUN      ] Image.CopyAssignmentOperator
[       OK ] Image.CopyAssignmentOperator (199 ms)
[ RUN      ] Image.References
[       OK ] Image.References (198 ms)
[ RUN      ] Image.CloudMechanics
[       OK ] Image.CloudMechanics (400 ms)
[ RUN      ] Image.XYZImage
[       OK ] Image.XYZImage (201 ms)
[ RUN      ] Image.ComputeCartesian
/home/lpdev/lovepark/ifm3d/modules/image/test/ifm3d-image-tests.cpp:421: Failure
Value of: std::equal(x_cam.begin<std::int16_t>(), x_cam.end<std::int16_t>(), x_computed.begin<std::int16_t>(), cmp)
  Actual: false
Expected: true
[  FAILED  ] Image.ComputeCartesian (401 ms)
[ RUN      ] Image.TimeStamp
[       OK ] Image.TimeStamp (3277 ms)
[ RUN      ] Image.IlluTemp
[       OK ] Image.IlluTemp (202 ms)
[----------] 10 tests from Image (5423 ms total)

[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (5427 ms total)
[  PASSED  ] 9 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Image.ComputeCartesian

 1 FAILED TEST
modules/image/test/CMakeFiles/check_image.dir/build.make:57: recipe for target 'modules/image/test/CMakeFiles/check_image' failed
make[3]: *** [modules/image/test/CMakeFiles/check_image] Error 1
CMakeFiles/Makefile2:741: recipe for target 'modules/image/test/CMakeFiles/check_image.dir/all' failed
make[2]: *** [modules/image/test/CMakeFiles/check_image.dir/all] Error 2
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:184: recipe for target 'check' failed
make: *** [check] Error 2
``` 

**For O3X.  with firmware 1.0.126 There is another issue** 

```
 make check [ 22%] Built target ifm3d_camera_shared
[ 37%] Built target ifm3d_framegrabber_shared
[ 44%] Built target ifm3d_image_shared
[ 51%] Built target gtest
[ 59%] Built target gtest_main
[ 70%] Built target ifm3d-image-tests
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from Image
[ RUN      ] Image.MoveCtor
/home/lpdev/lovepark/ifm3d/modules/image/test/ifm3d-image-tests.cpp:34: Failure
Value of: std::equal(copy_of_amp.begin<float>(), copy_of_amp.end<float>(), amp2.begin<float>())
  Actual: false
Expected: true
[  FAILED  ] Image.MoveCtor (1357 ms)
[ RUN      ] Image.MoveAssignmentOperator
/home/lpdev/lovepark/ifm3d/modules/image/test/ifm3d-image-tests.cpp:69: Failure
Value of: std::equal(copy_of_amp.begin<float>(), copy_of_amp.end<float>(), amp2.begin<float>())
  Actual: false
Expected: true
[  FAILED  ] Image.MoveAssignmentOperator (1252 ms)
[ RUN      ] Image.CopyCtor
/home/lpdev/lovepark/ifm3d/modules/image/test/ifm3d-image-tests.cpp:105: Failure
Value of: std::equal(amp.begin<float>(), amp.end<float>(), amp2.begin<float>())
  Actual: false
Expected: true
[  FAILED  ] Image.CopyCtor (1257 ms)
[ RUN      ] Image.CopyAssignmentOperator
/home/lpdev/lovepark/ifm3d/modules/image/test/ifm3d-image-tests.cpp:154: Failure
Value of: std::equal(amp.begin<float>(), amp.end<float>(), amp2.begin<float>())
  Actual: false
Expected: true
[  FAILED  ] Image.CopyAssignmentOperator (1512 ms)
[ RUN      ] Image.References
^Cmodules/image/test/CMakeFiles/check_image.dir/build.make:57: recipe for target 'modules/image/test/CMakeFiles/check_image' failed
make[3]: *** [modules/image/test/CMakeFiles/check_image] Interrupt
CMakeFiles/Makefile2:741: recipe for target 'modules/image/test/CMakeFiles/check_image.dir/all' failed
make[2]: *** [modules/image/test/CMakeFiles/check_image.dir/all] Interrupt
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Interrupt
Makefile:184: recipe for target 'check' failed
make: *** [check] Interrupt

```

**Comment by inbangsa** [comment]
@graugans  No I am running it on Linux

**Comment by graugans** [comment]
@tpanzarella  I do confirm that the unit test for cartesian compare are still failing for ``dev-0.11.2``

```
[       OK ] Image.CloudMechanics (397 ms)
[ RUN      ] Image.XYZImage
/home/ifm3d/ifm3d/modules/image/test/ifm3d-image-tests.cpp:288: Failure
Value of: (xyz.type() == CV_16SC3) || (xyz.type() == CV_32FC3)
  Actual: false
Expected: true
[  FAILED  ] Image.XYZImage (201 ms)
[ RUN      ] Image.ComputeCartesian
/home/ifm3d/ifm3d/modules/image/test/ifm3d-image-tests.cpp:466: Failure
Value of: std::equal(x_cam.begin<std::int16_t>(), x_cam.end<std::int16_t>(), x_computed.begin<std::int16_t>(), cmp)
  Actual: false
Expected: true
[  FAILED  ] Image.ComputeCartesian (414 ms)
[ RUN      ] Image.TimeStamp
[       OK ] Image.TimeStamp (4482 ms)
[ RUN      ] Image.IlluTemp
[       OK ] Image.IlluTemp (190 ms)
[----------] 10 tests from Image (6576 ms total)
````

**Comment by tpanzarella** [comment]
I will look into it. I know the ROS test is failing on 0.11.2 with an O3X. I expect O3X to fail on 0.11.1 (I created the 0.11.2 patch with the intent to fix it). I will see what I can do once I'm in the office. It will be a few hours.

**Comment by tpanzarella** [comment]
@inbangsa What is an O3D301?

**Comment by graugans** [comment]
@tpanzarella it is an O3D303 with 40x30 opening angle.
https://www.ifm.com/us/en/product/O3D301

**Comment by graugans** [comment]
@tpanzarella I still see the cartesian unit test failing...

**Comment by tpanzarella** [comment]
OK. So,  what is going on. Here is the h/w I am working with (O3D):

```
$ ifm3d dump | jq .ifm3d._
{
  "Date": "Tue Nov 13 10:30:43 2018",
  "HWInfo": {
    "Connector": "#!02_A300_C40_02452814_008023176",
    "Diagnose": "#!02_D322_C32_03038544_008023267",
    "Frontend": "#!02_F342_C34_17_00049_008023607",
    "Illumination": "#!02_I300_001_03106810_008001175",
    "MACAddress": "00:02:01:40:7D:96",
    "Mainboard": "#!02_M381_003_03181504_008022954",
    "MiraSerial": "0e30-59af-0ef7-0244"
  },
  "SWVersion": {
    "Algorithm_Version": "2.1.5",
    "Calibration_Device": "00:02:01:40:7d:96",
    "Calibration_Version": "0.9.0",
    "Diagnostic_Controller": "v1.0.33-92f88d349f-dirty",
    "IFM_Recovery": "unversioned",
    "IFM_Software": "1.23.1522",
    "Linux": "Linux version 3.14.34-rt31-yocto-standard-00009-ge4ab4d94f288-dirty (jenkins@dettlx190) (gcc version 4.9.2 (GCC) ) #1 SMP PREEMPT RT Tue Mar 13 16:06:07 CET 2018",
    "Main_Application": "1.0.33"
  },
  "ifm3d_version": 1102
}
```

**Comment by tpanzarella** [comment]
I can even get the tests to pass by rapidly waving my hand in front of the camera in close proximity to the lens which, as you know, will cause *many* "bad pixels".

**Comment by graugans** [comment]
@tpanzarella I have to recheck this, cause my camera does run with a default calib. Unfortunatly I have to leave now. Tomorrow I am on a business trip. So hopefully @inbangsa can assist you.

**Comment by inbangsa** [comment]
@tpanzarella There might not be invalid pixels in the frame captured. I always do this test by seeing the view of camera in iVA making sure it showing me invalid pixel ( seen as black). If this is there then try to run the test. 

I will also test this tommorow and will let you know the results.

**Comment by tpanzarella** [comment]
@inbangsa The patch to the code explicitly sets bad pixels to `0`. So, the idea is to *not* push this responsibility on the user but rather have the driver handle it directly in-line with pixel parsing.

**Comment by tpanzarella** [comment]
@inbangsa Oh, reading your comment closer... yes, I am ensuring there are bad pixels several ways: 1) I am rapidly waving my hand in front of the camera. It causes many bad pixels even on O3D; 2) Using an O3X pointed at scenes that are well beyond its capabilities also results in images with *many* bad pixels even without inducing them (i.e., hand waving).

**Comment by tpanzarella** [comment]
Here is the info on my O3X, I also cannot get the tests to fail with this device:

```
$ ifm3d dump | jq .ifm3d._
{
  "Date": "Tue Nov 13 10:55:58 2018",
  "HWInfo": {
    "MACAddress": "00:02:01:40:67:3F",
    "Mainboard": "#!02_M162_B30_12345678_008026357",
    "MiraSerial": "Not implemented"
  },
  "SWVersion": {
    "Algorithm_Version": "0.2.0",
    "Calibration_Device": "00:02:01:40:67:3f",
    "Calibration_Version": "1.0.0",
    "ELDK": "GOLDENEYE_YOCTO_HARDFP-371-06d9c894636352a6c93711c7284d02b0c794a527",
    "IFM_Software": "1.0.126",
    "Linux": "Linux version 3.14.34-rt31-yocto-standard-00029-gdf05c54-dirty (jenkins@dettlx152) (gcc version 4.9.2 (GCC) ) #1 SMP PREEMPT RT Wed Jan 24 13:40:11 CET 2018",
    "Main_Application": "0.4.1483"
  },
  "ifm3d_version": 1102
}
```

**Comment by tpanzarella** [comment]
OK, so it turns out that I had an O3D301 in the lab and this was the key to showing me why the tests were failing. And, I think this is what @inbangsa was trying to tell me. Sorry for misunderstanding Sachin and thanks for your insights. Anyway, you can see [this patch](https://github.com/ifm/ifm3d/commit/fc275ab1e612372eb496df4d4a2c13082cd9b118) to see the fix.

The idea is, now that we are setting bad pixels to `0` in the driver, when we compute the Cartesian data off-board, for those bad pixels (the zeros) we will compute their coords to be exactly equal to the translation vector from the extrinsic calibration on the camera (the transform from pmd chip to camera glass). For my O3D, the largest translational component was `tz` (in the optical frame, related to the `x` coord in the ifm3d camera frame) which was ~-10.3306 mm and when cast to `int16_t` was 10 mm and our test tolerance is 1 cm, so everything passed. When using the O3D301, `tz` was ~-13.9331 mm which casts to -14 mm and exceeds the tolerances of our test so the comparisons of the x-coords, for bad pixels, would fail. So, the fix is to back out the translation vector for the computed cartesian for bad pixels prior to doing the comparision. This is reflected in the linked to patch above.

@graugans and @inbangsa can you test this on your end?

**Comment by tpanzarella** [comment]
For completeness, I updated the ROS unit tests as well in [this patch](https://github.com/ifm/ifm3d-ros/commit/b889055a3e2ffdbd5e094e067e84bab1fbe8e538). They are passing for me.

**Comment by tpanzarella** [comment]
@inbangsa Can you send me some data so I can take a look? Basically, I'd like all array data from that test (confidence image, unit vectors, camera computed point cloud, radial distance image, extrinsic calibration, etc.) I can work with most formats, csv is fine if that is easiest for you to produce.

**Comment by tpanzarella** [comment]
Let's try this again @inbangsa I've pushed the latest [patch](https://github.com/ifm/ifm3d/commit/2bb5ae862099d983c4d9bbfbd34c9fa1fb38b2d8) to the unit tests. Your feedback is greatly appreciated.

**Comment by inbangsa** [comment]
@tpanzarella  cartesian compare test are working now. Here we are masking with confidence image again, which was done earlier also and then we decide to put all this in driver and user must not worry about confidence image.  

I think this pixels are good and zero value might be of the fact of rollover beyond camera range. Also the data provided contains the glass area which can also affect the distance value.

**Comment by tpanzarella** [comment]
> Here we are masking with confidence image again, which was done earlier also and then we decide to put all this in driver and user must not worry about confidence image.

We are doing this masking here simply for purposes of the test. We want to check our computed values against the values computed by the camera. So, only in the case of computing the Cartesian manually will the user need to mask out bad pixels. Masking the pixels at the driver level is a useful feature our users will come to rely upon. The primary question I wanted to deal with was do we mark bad pixels with `nan` or `0`. Ultimately the decision was to use `0` for several reasons, not the least of which is the inconsistency of data types used across cameras (i.e., there is no such thing as a `nan` for an integral type) so, to keep things camera agnostic `0` is being used. Further, given the practicalities of the hardware, using `0` as a sentinel value to flag pixels as "invalid" seems reasonable -- i.e., there is no plausible scenario where a good pixel will measure a `0` radial distance or `(0,0,0)` Cartesian coordinate. This leads to my standing questions as to how could we have "good" pixels with a radial distance value of `0`? And, if this is a possibility (i.e., the hardware may return data that look like this), should we in the driver "fix" it -- i.e., should we be consulting both the confidence image *and* the radial distance image to flag pixels as bad in the other arrays?

> I think this pixels are good and zero value might be of the fact of rollover beyond camera range. Also the data provided contains the glass area which can also affect the distance value.

When you say "rollover in the camera range" I assume you mean the ambiguity range of the selected imager type? Assuming a single frequency (which we use by default in the unit tests), you are proposing that those 5 pixels likely measured 1 mm beyond the max "allowable" by the phase shift measurement which would "rollover" to exactly 0 mm. I suppose that is a possibility. Below is a histogram of the radial distances from the data you sent over. For reference, the max radial distance was 5080 mm (max on-camera computed Cartesian x-coord (z in the optical frame)) was 5046 mm.

rdis_hist

**Comment by inbangsa** [comment]
@tpanzarella Thanks for all the information.

**Pull request closed without merging**
