### PR TITLE
Add support for retrieving the intrinsic Parameters from an O3D3xx camera

### PR DESCRIPTION
**Pull request by graugans**
This will fix the issue #62 by adding a ``std::vector`` instead of a JSON object.

### CODE REVIEW

**Comment by tpanzarella** [comment]
@graugans @Bangadkar Do you plan to expose this functionality in `ifm3d-ros`? This could be modeled after [the implementation in royale-ros](https://github.com/lovepark/royale-ros/blob/master/src/camera_nodelet.cpp#L358)

**Comment by graugans** [comment]
@tpanzarella we have some ongoing internal discussion about those parameters. So please no hurry with merging. The plan is to have it in ROS after we have finalized it.

**Comment by tpanzarella** [comment]
OK. Let me know the result of your conversations. I won't merge until I hear from you.

**Comment by graugans** [comment]
@tpanzarella we have verified with algo department if all values are passed correctly. There will be another Pull-Request to add support for the inverse intrinsic parameters as-well. But those also needs a change in the FW. To have full backward compatibility this will need another chunk ID. When this is merged there will be a Rull-Request on the ifm3d-examples project as-well.

The update on the ROS part  @inbangsa and team will take care of after both intrinsic parameters are available in ifm3d.

**Pull request merged**
